#!/usr/bin/env python
import sys
from enum import Enum
import re


commit_types = ["FIX", "FEAT", "BREAKING CHANGE"]

class bcolors(str, Enum):
    OK = "\033[92m"
    INFO = "\033[94m"
    WARNING = "\033[93m"
    ERROR = "\033[91m"
    BOLD = "\033[1m"
    ENDC = "\033[0m"


class Level(str, Enum):
    OK = "OK"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


def print_with_color(message: str, level: Level):
    print(
        bcolors[level] + bcolors.BOLD + f"{level}: [Policy] " + message + bcolors.ENDC
    )


def get_key_word(message: str):
    split = message[0].split(" [")
    return split[0]


def check_jira_pattern(message: str):
    padrao = re.compile(r'\[[A-Za-z]+-\d+\]')
    split = message[0].split(":")
    print(padrao.search(split[0]))
    return padrao.search(split[0])


def check_commit_msg_pattern():
    msg_temp_file = sys.argv[1]

    with open(msg_temp_file, "r") as f_msg:
        lines = f_msg.readlines()

    lines = [l for l in lines if not l.strip().startswith("#")]

    has_warning = False
    if lines[0].find(":") == -1:
        message = "There should be a key word in the beginnig of the commit to clarify his objective"
        print_with_color(message, Level.ERROR)
        return 1

    if get_key_word(lines) not in commit_types:
        message = "The key word of the commit should be one of these: FIX, WIP, ADD, CREATE, CHANGE, IMPROVE, REMOVE"
        print_with_color(message, Level.ERROR)
        return 1

    if not check_jira_pattern(lines):
        message = "The commit message should mention the Jira card associated to it"
        print_with_color(message, Level.ERROR)
        return 1

    if not has_warning:
        message = "The commit message has the required pattern."
        print_with_color(message, Level.OK)
        return 0


if __name__ == "__main__":
    raise SystemExit(check_commit_msg_pattern())
