name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false
      - name: Google Chat Notification
        run: |
            curl --location --request POST '${{ secrets.WEBHOOK }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "cards": [
                    {
                        "header": {
                            "title": "Release alert",
                        },
                        "sections": [
                            {
                                "widgets": [
                                    {
                                      "keyValue": {
                                            "topLabel": "Creator",
                                            "content": "${{ github.event }}"
                                        },
                                    },
                                    {
                                      "keyValue": {
                                            "topLabel": "Version",
                                            "content": "${{ github.ref }}"
                                        }
                                    },
                                    {
                                      "keyValue": {
                                            "topLabel": "Body",
                                            "content": "- ${{ steps.build_changelog.outputs.changelog }}"
                                        }
                                    },
                                    {
                                        "buttons": [
                                            {
                                                "textButton": {
                                                    "text": "OPEN RELEASE",
                                                    "onClick": {
                                                        "openLink": {
                                                            "url": "${{ steps.create_release.outputs.html_url }}"
                                                        }
                                                    }
                                                }
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }'