name: Release notify

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        run: |
            curl --location --request POST '${{ secrets.WEBHOOK }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "cards": [
                    {
                        "header": {
                            "title": "Release alert",
                            "subtitle": "PR: #${{ github.event.release.title }}"
                        },
                        "sections": [
                            {
                                "widgets": [
                                    {
                                      "keyValue": {
                                            "topLabel": "Creator",
                                            "content": "${{ github.event.release.author.login }}"
                                        },
                                    },
                                    {
                                      "keyValue": {
                                            "topLabel": "Version",
                                            "content": "${{ github.event.release.tag_name }}"
                                        }
                                    },
                                    {
                                      "keyValue": {
                                            "topLabel": "Body",
                                            "content": "- ${{ github.event.release.body }}"
                                        }
                                    },
                                    {
                                        "buttons": [
                                            {
                                                "textButton": {
                                                    "text": "OPEN PR",
                                                    "onClick": {
                                                        "openLink": {
                                                            "url": "${{ github.event.release.html_url }}"
                                                        }
                                                    }
                                                }
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }'