on:
  pull_request:
   types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "PR Alert",
                          "subtitle": "PR: #${{ github.event.pull_request.title }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                     "keyValue": {
                                          "topLabel": "Creator",
                                          "content": "${{ github.event.pull_request.user.login }}"
                                      },
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Title",
                                          "content": "${{ github.event.pull_request.title }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assigned Labels",
                                          "content": "- ${{ join(github.event.pull_request.labels.*.name) }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Reviewer",
                                          "content": "- ${{ join(github.event.pull_request.requested_reviewers.*.login) }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Body",
                                          "content": "- ${{ github.event.pull_request.body }}"
                                      }
                                   },
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "OPEN PR",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.pull_request.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
